set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]

set_property PACKAGE_PIN G6 [get_ports get_bluetooth]
set_property IOSTANDARD LVCMOS33 [get_ports get_bluetooth]

set_property PACKAGE_PIN H4 [get_ports XDCS]
set_property IOSTANDARD LVCMOS33 [get_ports XDCS]

set_property PACKAGE_PIN H1 [get_ports XRSET]
set_property IOSTANDARD LVCMOS33 [get_ports XRSET]

set_property PACKAGE_PIN G1 [get_ports DREQ]
set_property IOSTANDARD LVCMOS33 [get_ports DREQ]

set_property PACKAGE_PIN H2 [get_ports XCS]
set_property IOSTANDARD LVCMOS33 [get_ports XCS]

set_property PACKAGE_PIN G4 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]

set_property PACKAGE_PIN G2 [get_ports SI]
set_property IOSTANDARD LVCMOS33 [get_ports SI]

set_property PACKAGE_PIN F3 [get_ports SO]
set_property IOSTANDARD LVCMOS33 [get_ports SO]

set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33a [get_ports led[14]]
set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN P17 [get_ports prev]
set_property IOSTANDARD LVCMOS33 [get_ports prev]
set_property PACKAGE_PIN M17 [get_ports next]
set_property IOSTANDARD LVCMOS33 [get_ports next]
set_property PACKAGE_PIN M18 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN P18 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports down]

set_property PACKAGE_PIN J17 [get_ports {disp7_shf[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[0]}]
set_property PACKAGE_PIN J18 [get_ports {disp7_shf[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[1]}]
set_property PACKAGE_PIN T9 [get_ports {disp7_shf[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[2]}]
set_property PACKAGE_PIN J14 [get_ports {disp7_shf[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[3]}]
set_property PACKAGE_PIN P14 [get_ports {disp7_shf[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[4]}]
set_property PACKAGE_PIN T14 [get_ports {disp7_shf[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[5]}]
set_property PACKAGE_PIN K2 [get_ports {disp7_shf[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[6]}]
set_property PACKAGE_PIN U13 [get_ports {disp7_shf[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_shf[7]}]

set_property PACKAGE_PIN T10 [get_ports {disp7_odata[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[0]}]
set_property PACKAGE_PIN R10 [get_ports {disp7_odata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[1]}]
set_property PACKAGE_PIN K16 [get_ports {disp7_odata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[2]}]
set_property PACKAGE_PIN K13 [get_ports {disp7_odata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[3]}]
set_property PACKAGE_PIN P15 [get_ports {disp7_odata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[4]}]
set_property PACKAGE_PIN T11 [get_ports {disp7_odata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[5]}]
set_property PACKAGE_PIN L18 [get_ports {disp7_odata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {disp7_odata[6]}]

set_property PACKAGE_PIN H15 [get_ports disp7_dot]
set_property IOSTANDARD LVCMOS33 [get_ports disp7_dot]

set_property PACKAGE_PIN R12 [get_ports {led_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rgb[0]}]
set_property PACKAGE_PIN M16 [get_ports {led_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rgb[1]}]
set_property PACKAGE_PIN N15 [get_ports {led_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rgb[2]}]

set_property PACKAGE_PIN T10 [get_ports {display[0]}]
set_property PACKAGE_PIN R10 [get_ports {display[1]}]
set_property PACKAGE_PIN K16 [get_ports {display[2]}]
set_property PACKAGE_PIN K13 [get_ports {display[3]}]
set_property PACKAGE_PIN P15 [get_ports {display[4]}]
set_property PACKAGE_PIN T11 [get_ports {display[5]}]
set_property PACKAGE_PIN L18 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]

set_property PACKAGE_PIN C17 [get_ports {link[0]}]
set_property PACKAGE_PIN D18 [get_ports {link[1]}]
set_property PACKAGE_PIN E17 [get_ports {link[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {link[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {link[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {link[0]}]

set_property PACKAGE_PIN C17 [get_ports blue_link]
set_property IOSTANDARD LVCMOS33 [get_ports blue_link]

set_property PACKAGE_PIN G16 [get_ports iA]
set_property PACKAGE_PIN F16 [get_ports iB]
set_property PACKAGE_PIN D14 [get_ports SW]
set_property IOSTANDARD LVCMOS33 [get_ports iA]
set_property IOSTANDARD LVCMOS33 [get_ports iB]
set_property IOSTANDARD LVCMOS33 [get_ports SW]

set_property PACKAGE_PIN D18 [get_ports alarm_sig]
set_property IOSTANDARD LVCMOS33 [get_ports alarm_sig]
